name: erb_shared
description: ERb libs - generic utils (including extensions, ...)
version: 0.0.1
homepage: https://github.com/nguyenhan-se/erb_flutter_boilerplate

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
