include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # directives_ordering: true

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"

  errors:
    invalid_annotation_target: ignore
