name: erb_flutter_boilerplate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this
    sdk: flutter

  cupertino_icons: ^1.0.6

  # logger
  talker_flutter: ^3.6.0
  talker_dio_logger: ^2.4.0

  # dart utils
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  fpdart: ^1.1.0
  fast_immutable_collections: ^9.2.0
  retrofit: ^4.0.3
  dart_mappable: ^4.1.0
  internet_connection_checker_plus: ^2.1.0

  # i18n
  slang: ^3.27.0
  slang_flutter: ^3.27.0
  #https://github.com/flutter/flutter/issues/139861
  intl: ^0.18.1

  # db local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # flutter utils
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  auto_route: ^7.8.4
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  local_auth: ^2.1.7
  flutter_flavor: ^3.1.3
  app_settings: ^5.1.1
  responsive_framework: ^1.1.1
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^16.2.0

  # Device Identification
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  android_id: ^0.3.6

  # flutter widgets
  cached_network_image: ^3.3.0
  infinite_scroll_pagination: ^4.0.0

  # Firebase service
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # annotations
  riverpod_annotation: ^2.3.3
  reactive_forms_annotations: ^4.2.0

  # Mock

  # Local packages
  env:
    path: packages/env
  assets:
    path: packages/assets
  app_constants:
    path: packages/app_constants
  erb_shared:
    path: packages/erb_shared
  erb_ui:
    path: packages/erb_ui
  erb_infinite_scroll:
    path: packages/erb_infinite_scroll

dev_dependencies:
  flutter_test:
    sdk: flutter
  # workflow
  melos: ^3.4.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.3.8

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

  # generators
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  slang_build_runner: ^3.27.0
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.6
  reactive_forms_generator: ^4.3.0
  hive_generator: ^2.0.1
  dart_mappable_builder: ^4.1.0
  husky: 0.1.6
  lint_staged: 0.4.2

lint_staged:
  "*/**.dart": dart format --fix
flutter:
  uses-material-design: true
