name: erb_flutter_boilerplate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this
    sdk: flutter

  cupertino_icons: ^1.0.2

  # logger
  talker_flutter: ^3.5.4
  talker_dio_logger: ^2.3.1

  # dart utils
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  fpdart: ^1.1.0
  fast_immutable_collections: ^9.1.6
  retrofit: ^4.0.3
  tinycolor2: ^3.0.1
  dart_mappable: ^4.0.1

  # i18n
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  intl: ^0.18.1

  # db local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # flutter utils
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  auto_route: ^7.8.4
  url_launcher: ^6.2.1
  dynamic_color: ^1.6.8
  permission_handler: ^11.1.0
  local_auth: ^2.1.7
  flutter_flavor: ^3.1.1
  app_settings: ^5.1.1
  responsive_framework: ^1.1.1
  flutter_cache_manager: ^3.3.1

  # Device Identification
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  android_id: ^0.3.6

  # flutter widgets
  cached_network_image: ^3.3.0

  # annotations
  riverpod_annotation: ^2.3.3
  reactive_forms_annotations: ^4.2.0

  # Mock

  # Local packages
  env:
    path: packages/env
  assets:
    path: packages/assets
  app_constants:
    path: packages/app_constants
  erb_shared:
    path: packages/erb_shared
  erb_ui:
    path: packages/erb_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  # workflow
  melos: ^3.2.0
  change_app_package_name: ^1.1.0

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.7

  # generators
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  slang_build_runner: ^3.25.0
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.3
  reactive_forms_generator: ^4.3.0
  hive_generator: ^2.0.1
  dart_mappable_builder: ^4.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta-Black.otf
          weight: 900
        - asset: assets/fonts/Averta-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Averta-Bold.otf
          weight: 700
        - asset: assets/fonts/Averta-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Averta-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Averta-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Averta-Extrathin.otf
          weight: 100
        - asset: assets/fonts/Averta-ExtrathinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Averta-Light.otf
          weight: 300
        - asset: assets/fonts/Averta-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Averta-Regular.otf
        - asset: assets/fonts/Averta-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Averta-Semibold.otf
          weight: 600
        - asset: assets/fonts/Averta-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Averta-Thin.otf
          weight: 200
        - asset: assets/fonts/Averta-ThinItalic.otf
          weight: 200
          style: italic
