name: erb_ui
description: ERb libs - simple, generic widgets
version: 0.0.4

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  erb_shared:
    path: ../erb_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
