// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBy7AxuUHYi9fJgMvblRb1DJmOtEIYeM',
    appId: '1:983443814070:web:ba7fd8014ba2d051da5817',
    messagingSenderId: '983443814070',
    projectId: 'erb-boilerplate',
    authDomain: 'erb-boilerplate.firebaseapp.com',
    storageBucket: 'erb-boilerplate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjJbt7CBjEJ7PYVdgoW1lQkKlNb4MT4g',
    appId: '1:983443814070:android:49accab1e1fecfeeda5817',
    messagingSenderId: '983443814070',
    projectId: 'erb-boilerplate',
    storageBucket: 'erb-boilerplate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgClhHlT-IqQtRPN2LQTobWCJuOqhttc',
    appId: '1:983443814070:ios:264d12827bb264d0da5817',
    messagingSenderId: '983443814070',
    projectId: 'erb-boilerplate',
    storageBucket: 'erb-boilerplate.appspot.com',
    iosBundleId: 'com.example.erbFlutterBoilerplatee',
  );
}
