name: env
description: A new Flutter package which provides environment variables for the app. These variables can also be obfuscated.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_flavor: ^3.1.3
  firebase_core: ^2.24.2

  flutter_test:
    sdk: flutter

flutter:
