name: assets
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true

flutter:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta-Black.otf
          weight: 900
        - asset: assets/fonts/Averta-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Averta-Bold.otf
          weight: 700
        - asset: assets/fonts/Averta-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Averta-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Averta-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Averta-Extrathin.otf
          weight: 100
        - asset: assets/fonts/Averta-ExtrathinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Averta-Light.otf
          weight: 300
        - asset: assets/fonts/Averta-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Averta-Regular.otf
        - asset: assets/fonts/Averta-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Averta-Semibold.otf
          weight: 600
        - asset: assets/fonts/Averta-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Averta-Thin.otf
          weight: 200
        - asset: assets/fonts/Averta-ThinItalic.otf
          weight: 200
          style: italic
