name: assets
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  # Must specify full path to each asset, directories will not work
  # since this is in a package. All assets must also be in the lib directory.
  #
  # Run the generator with `melos run assets`
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: true
