#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`


TYPE="feat|fix|refactor|perf|style|test|docs|build|ops|chore"
PLATFORM='.{1,20}'

PATTERN="^($TYPE)\(($PLATFORM)\): "

if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, see example: <type>(<optional scope 1-> 20 character>): <description>"
  exit 1
fi




